### PR TITLE
features, refactoring and fixes for 1.0.0

### PR DESCRIPTION
**Pull request by johguentner**
- unions types for filters and sorts
- phpunit --> pest
- drop support for PHP 7.4

### CODE REVIEW

**Comment by ijpatricio** [comment]
Hey @johguentner 
I'm playing with Notion API and Laravel 10, so this `dev` branch would be the one to go.
Is it usable "at my own risk", or is it a target of further developments?

**Comment by mechelon** [comment]
Hey @ijpatricio 

We plan to release the 2.0 version with Laravel 10 support in the next 1-3 days but until now the dev branch is good to go ☺️ we don't plan any further development on this except for maybe some minor adjustments.

**Comment by ijpatricio** [comment]
Excellent! Thank you, @mechelon 

PS: Your talk on explaining Inertia on LaraconEU was brilliant 👏

**Comment by richardhj** [comment]
Can you update the Notion-Version header to the latest "2022-06-28" when doing this release?
You are currently using version "2021-05-13," which is behind - for example, you cannot fetch "Phone" properties.

**Comment by johguentner** [comment]
> Can you update the Notion-Version header to the latest "2022-06-28" when doing this release? You are currently using version "2021-05-13," which is behind - for example, you cannot fetch "Phone" properties.

Hi @richardhj,
thanks for your question. This is not so easily possible, because there are other breaking changes introduced by Notion since then (for example https://developers.notion.com/page/changelog#may-19-2021). We want to solve those asap after releasing 1.0.0. 
We have prepared a new testing-strategy within the branch [record-and-fake-tests](https://github.com/5am-code/laravel-notion-api/tree/refactor/record-and-fake-tests) to allow better refactoring of those breaking changes.

btw: The `PhoneNumber` property should be supported without an issue. Do you have an example, which does not work?

**Pull request merged**
