### PR TITLE
Patch for typo, type-check, removing unused file and block-update-functionality

### PR DESCRIPTION
**Pull request by johguentner**

### CODE REVIEW

**Comment by johguentner** [comment]
I can't see any issues localy and tests are running perfectly. 👌
What do you think @mechelon, should we merge this into main, and releaes with the next version, or should we create a patch-version? 🤔

**Comment by mechelon** [comment]
I think it's not really a bug, so a release with the next version is okay :)

**Comment by mechelon** [comment]
I would keep it in dev until next release, so we don't forget about it. (writing release notes from commit messages... 😅 )

**Comment by johguentner** [comment]
> I would keep it in dev until next release, so we don't forget about it. (writing release notes from commit messages... 😅 )

Yes, same thought here. Let's do it that way 👍

**Pull request merged**
