### PR TITLE
Laravel 11.x Compatibility

### PR DESCRIPTION
**Pull request by laravel-shift**
This is an automated pull request from [Shift](https://laravelshift.com) to update your package code and dependencies to be compatible with Laravel 11.x.

**Before merging**, you need to:

- Checkout the `l11-compatibility` branch
- Review **all** comments for additional changes
- Thoroughly test your package

If you do find an issue, please report it by commenting on this PR to help improve future automation.

### CODE REVIEW

**Comment by laravel-shift** [comment]
:warning: The latest version of Laravel has a dependency for `phpunit/phpunit` of `^10.5`. If you would like to also upgrade your tests, you may run the [PHPUnit 10 Shift](https://laravelshift.com/upgrade-phpunit-10) for free.

**Comment by laravel-shift** [comment]
:warning: Shift detected GitHub Actions which run jobs using a version `matrix`. Shift attempted to [update your configuration](https://github.com/5am-code/laravel-notion-api/pull/172/commits/b43754972b81f1f54be57f6d32628ffb0bab77dc?w=1) for Laravel 11. However, you should review these changes to ensure the desired combination of versions are built for your package.

**Comment by laravel-shift** [comment]
:alembic: **Using this package?** If you would like to help test these changes or believe them to be compatible, you may update your project to reference this branch.

To do so, temporarily add Shift's fork to the `repositories` property of your `composer.json`:

```json
{
    "repositories": [
        {
            "type": "vcs",
            "url": "https://github.com/laravel-shift/laravel-notion-api.git"
        }
    ]
}
```

Then update your dependency constraint to reference this branch:

```json
{
    "require": {
        "fiveam-code/laravel-notion-api": "dev-l11-compatibility",
    }
}
```

Finally, run: `composer update`

**Comment by hermanschutte** [comment]
Any chance getting this PR merged? Would love to use this in a new Laravel 11 project.

**Comment by johguentner** [comment]
> Any chance getting this PR merged? Would love to use this in a new Laravel 11 project.

I'm having a look into this and trying to merge this soon.

**Comment by johguentner** [comment]
With #174 `laravel-notion-api` (v1.2.0) supports Laravel 11.x
- all tests are running smoothly and I tested various scenarious directly with the Notion API
- if you find any issues, while running `laravel-notion-api` with Laravel 11.x, please open an issue and description what happened; thank you!

**Pull request merged**
